services:
  mongo:
    image: mongo:5.0.3
    ports:
      - 27017:27017
    command: mongod --noauth --bind_ip 0.0.0.0
    # To enable authentication, remove the "--noauth" flag and uncomment the following environment variables:
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: <your_username>
    #   MONGO_INITDB_ROOT_PASSWORD: <your_password>

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    # To enable authentication, uncomment and set the following environment variables:
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: <your_username>
      # ME_CONFIG_MONGODB_ADMINPASSWORD: <your_password>
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
